inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

# This is not supported for Mongoid
Rails/FindBy:
  Enabled: false

Rails/SaveBang:
  AllowedReceivers:
    - indices # for elasticsearch
