development:
  clients:
    default:
      uri: <%= ENV["MONGODB_URI"] || "mongodb://localhost/licence_finder_development" %>
      options:
        write:
          w: 1
        read:
          mode: :primary
test:
  clients:
    default:
      uri: <%= ENV["MONGODB_URI"] || "mongodb://localhost/licence_finder_test" %>
      options:
        write:
          w: 1
        read:
          mode: :primary
        max_retries: 1
        retry_interval: 0
production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        write:
          w: 1
        read:
          mode: :primary
        retry_interval: 120
